# Generated by Django 4.0.6 on 2022-08-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Noun', models.CharField(max_length=100)),
                ('Datebirth', models.CharField(max_length=100)),
                ('Adress', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=100)),
            ],
        ),
    ]
