# Generated by Django 4.0.6 on 2022-08-07 11:05

from django.db import migrations, models
import enum


class Migration(migrations.Migration):

    dependencies = [
        ('Transliteration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Noun', models.CharField(max_length=100)),
                ('Datebirth', models.DateField(default=enum.auto)),
                ('Adress', models.CharField(blank=True, default='ABCD', max_length=100)),
                ('Nationality', models.CharField(max_length=100)),
                ('Place_of_birth', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.DeleteModel(
            name='Notrans',
        ),
    ]
